/*******************************************************************************
 * All the number values in the game that should be customizable in one place
 * to change the balance of the game
 ******************************************************************************/
this.BalanceValues = {
  STATE_AGENT_COUNT: 10,
  STATE_AGENT_DETECTABILITY_RATE: 10,
  STATE_AGENT_TURN_TO_FREEZE: 1,

  TERRORIST_MONEY_RESERVES: 100,
  TERRORIST_MONEY_GOAL: 25,
  TERRORIST_MONEY_PER_TURN: 6,
  TERRORIST_STARTING_BALANCE: 5,
  TERRORIST_STARTING_NODE_RESERVES: 10,
  TERRORIST_TIME_TO_MAINTENANCE: 1,
  TERRORIST_MAINTENANCE_COSTS: 1,
  TERRORIST_MAX_TRANSACTIONS_PER_TURN: 5,
  TERRORIST_COURIER_COST: 0.5,
  TERRORIST_COURIER_DELAY: 1,

  FAKE_MONEY_MAX_AMOUNT: 3,
  FAKE_MONEY_SMALL_AMOUNT_MIN: 1,
  FAKE_MONEY_SMALL_AMOUNT_MAX: 5,
  FAKE_MONEY_MEDIUM_AMOUNT_MIN: 6,
  FAKE_MONEY_MEDIUM_AMOUNT_MAX: 10,
  FAKE_MONEY_LARGE_AMOUNT_MIN: 11,
  FAKE_MONEY_LARGE_AMOUNT_MAX: 30,
  FAKE_MONEY_SMALL_MONEY_CHANCE: 85,
  FAKE_MONEY_MEDIUM_MONEY_CHANCE: 10,
  FAKE_MONEY_CHANCE_TO_MOVE: 35,
  FAKE_MONEY_COURIER_CHANCE: 15,

  NETWORK_CLUSTER_COUNT: 3,
  NETWORK_TERRORIST_COUNT: 3,
  NETWORK_MIN_BANK_NODES_PER_CLUSTER: 3,
  NETWORK_MAX_BANK_NODES_PER_CLUSTER: 4,
  NETWORK_MIN_HAWALA_NODES_PER_CLUSTER: 1,
  NETWORK_MAX_HAWALA_NODES_PER_CLUSTER: 2,
  NETWORK_MIN_LINKS_PER_NODE: 2,
  NETWORK_MAX_LINKS_PER_NODE: 3,
  NETWORK_MIN_LINK_TRAVEL_TIME: 1,
  NETWORK_MAX_LINK_TRAVEL_TIME: 2,
  NETWORK_MIN_LINKS_WITH_PLURAL_TRAVEL_TIME: 3,
  NETWORK_MAX_LINKS_WITH_PLURAL_TRAVEL_TIME: 5,

  NETWORK_STAT_FAKE_LEAD_PROBABILITY: 70, // Starting with the first cluster, the % chance a fake lead will be spotted.
  NETWORK_STAT_FAKE_LEAD_FALLOFF: 50,     // Each cluster after the first will take the probability of the previous cluster and multiply it by this percentage.
}
